from alfi_3f.problem import NonNewtonianProblem_Sup
from alfi_3f.problem import NonNewtonianProblem_TSup
from alfi_3f.problem import NonNewtonianProblem_LSup
from alfi_3f.problem import NonIsothermalProblem_Sup
from alfi_3f.problem import NonNewtonianProblem_up
from alfi_3f.problem import NonNewtonianProblem_Tup
from alfi_3f.problem import NonNewtonianProblem_Lup
from alfi_3f.problem import NonIsothermalProblem_up
from alfi_3f.solver import ScottVogeliusSolver
from alfi_3f.solver import P1P1Solver
from alfi_3f.solver import P1P0Solver
from alfi_3f.other_models.oldroydB import OldroydBSVSolver
from alfi_3f.driver import *
from alfi.relaxation import *
from alfi.bary import *
